import { Link } from 'react-router-dom'
import type { AssessmentReport, Severity } from '../pentest/types'

const severityClass: Record<Severity, string> = {
  Critical: 'bg-red-700 text-white',
  High: 'bg-orange-600 text-white',
  Medium: 'bg-amber-500 text-black',
  Low: 'bg-yellow-400 text-black',
  Info: 'bg-sky-500 text-white',
}

type ReportViewProps = {
  report: AssessmentReport
  showActions?: boolean
}

const ReportView = ({ report, showActions = true }: ReportViewProps) => {
  const total =
    report.findingCounts.Critical +
    report.findingCounts.High +
    report.findingCounts.Medium +
    report.findingCounts.Low +
    report.findingCounts.Info

  return (
    <article className="report-document">
      {showActions && (
        <div className="report-toolbar print:hidden">
          <Link to="/audits" className="text-sm text-gray-400 hover:text-white">
            All assessments
          </Link>
          <button type="button" className="btn-primary text-sm" onClick={() => window.print()}>
            Export PDF
          </button>
        </div>
      )}

      <section className="report-cover">
        <p className="report-kicker">Enterprise-Grade Security</p>
        <p className="report-confidential">Public · Penetration Test Report</p>
        <h1 className="report-title">External Penetration Test</h1>
        <p className="report-subtitle">{report.hostname}</p>
        <p className="text-gray-400 max-w-3xl leading-relaxed">
          An external, black-box security assessment conducted under the OWASP Web Security Testing Guide, PTES and NIST
          SP 800-115.
        </p>
        <dl className="report-meta-grid">
          <div>
            <dt>Target</dt>
            <dd>{report.target}</dd>
          </div>
          <div>
            <dt>Assessment date</dt>
            <dd>{report.assessmentDate}</dd>
          </div>
          <div>
            <dt>Posture</dt>
            <dd>{report.posture}</dd>
          </div>
          <div>
            <dt>Prepared by</dt>
            <dd>{report.preparedBy}</dd>
          </div>
        </dl>
        <p className="text-sm text-gray-500 mt-8">
          Report reference {report.reference} · Classification: {report.classification} — generated by the Block08 toolkit
        </p>
      </section>

      <section className="report-section">
        <h2>01 · Executive summary</h2>
        <h3>Assessment at a glance</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <div className="report-stat">
            <p className="report-stat-label">Overall risk</p>
            <p className="report-stat-value">{report.overallRisk}</p>
          </div>
          <div className="report-stat">
            <p className="report-stat-label">Total findings</p>
            <p className="report-stat-value">{total}</p>
          </div>
          <div className="report-stat">
            <p className="report-stat-label">Critical + High</p>
            <p className="report-stat-value">{report.findingCounts.Critical + report.findingCounts.High}</p>
          </div>
          <div className="report-stat">
            <p className="report-stat-label">Controls verified</p>
            <p className="report-stat-value">{report.controls.length}</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-3 mb-8 text-sm">
          <span>Critical {report.findingCounts.Critical}</span>
          <span>High {report.findingCounts.High}</span>
          <span>Medium {report.findingCounts.Medium}</span>
          <span>Low {report.findingCounts.Low}</span>
          <span>Info {report.findingCounts.Info}</span>
        </div>
        <p className="text-gray-300 leading-relaxed">{report.executiveSummary}</p>
      </section>

      <section className="report-section">
        <h2>02 · Scope & rules of engagement</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <h3>In scope</h3>
            <p className="text-gray-300">{report.scope.inScope}</p>
          </div>
          <div>
            <h3>Rules of engagement</h3>
            <p className="text-gray-300">{report.scope.rules}</p>
          </div>
          <div>
            <h3>Methodology</h3>
            <p className="text-gray-300">{report.scope.methodology}</p>
          </div>
          <div>
            <h3>Tooling</h3>
            <p className="text-gray-300">{report.scope.tooling.join(', ')}</p>
          </div>
        </div>
      </section>

      <section className="report-section">
        <h2>03 · Findings register</h2>
        <div className="overflow-x-auto">
          <table className="report-table">
            <thead>
              <tr>
                <th>Severity</th>
                <th>ID</th>
                <th>Finding</th>
                <th>WSTG</th>
                <th>CWE</th>
              </tr>
            </thead>
            <tbody>
              {report.findings.map((finding) => (
                <tr key={finding.id}>
                  <td>
                    <span className={`px-2 py-1 rounded text-xs font-semibold ${severityClass[finding.severity]}`}>
                      {finding.severity}
                    </span>
                  </td>
                  <td className="font-mono text-sm">{finding.id}</td>
                  <td>{finding.title}</td>
                  <td className="font-mono text-sm">{finding.wstg}</td>
                  <td className="font-mono text-sm">{finding.cwe}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="report-section">
        <h2>04 · Detailed findings</h2>
        <div className="space-y-8">
          {report.findings.map((finding) => (
            <div key={finding.id} className="report-finding">
              <div className="flex flex-wrap items-center gap-3 mb-3">
                <span className={`px-2 py-1 rounded text-xs font-semibold ${severityClass[finding.severity]}`}>
                  {finding.severity}
                </span>
                <h3 className="text-xl font-bold text-white m-0">{finding.title}</h3>
              </div>
              <p className="text-sm text-gray-500 mb-4 font-mono">
                {finding.id} · {finding.wstg} · {finding.cwe} · CVSS {finding.cvss}
              </p>
              <p className="text-xs tracking-widest uppercase text-primary-500 mb-2">Evidence</p>
              <p className="text-gray-300 mb-4">{finding.evidence}</p>
              <p className="text-xs tracking-widest uppercase text-primary-500 mb-2">Recommendation</p>
              <p className="text-gray-300">{finding.recommendation}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="report-section">
        <h2>05 · Positive assurance</h2>
        <p className="text-gray-400 mb-6">
          The following {report.controls.length} defences were tested and found to be correctly implemented.
        </p>
        <ul className="space-y-4">
          {report.controls.map((control) => (
            <li key={control.title} className="report-control">
              <p className="font-semibold text-white">✓ {control.title}</p>
              <p className="text-gray-400 text-sm">{control.detail}</p>
            </li>
          ))}
        </ul>
      </section>

      <section className="report-section">
        <h2>07 · Remediation roadmap</h2>
        <ol className="space-y-4 list-decimal list-inside text-gray-300">
          {report.roadmap.map((step) => (
            <li key={step}>{step}</li>
          ))}
        </ol>
      </section>

      <section className="report-section">
        <h2>08 · Assurance statement</h2>
        <p className="text-gray-300 leading-relaxed mb-6">{report.assurance}</p>
        <p className="text-sm text-gray-500">
          Standards applied: OWASP WSTG v4.2 · PTES · NIST SP 800-115 · CVSS 3.1 · CWE
        </p>
      </section>

      <footer className="report-end">
        <p>Prepared & attested by Block08 Security Audits · Offensive Security Practice</p>
        <p>
          {report.reference} · {report.assessmentDate} · {report.classification}
        </p>
        <p className="mt-4">
          This report was executed and generated by the Block08 assessment toolkit from live tool output. It is not
          AI-generated.
        </p>
      </footer>
    </article>
  )
}

export default ReportView
